[package]
name = "easy-image-grayscale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.8.0"
iced_native = "0.9.1"
image = {version = "0.24.5", features = ["png", "jpeg"]}


